/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Return the most recent runs (newest first), capped at `limit`.
         */
        get: operations["list_runs_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Create a run row and spawn the orchestrator in the background.
         *
         *     Returns 202 with `{run_id, status, started_at, location}`. The
         *     `Location` header also points to `/runs/<id>` for the standard REST
         *     pattern.
         *
         *     Returns 409 with `{detail, active_run_id}` if another run is already
         *     in flight (uniq_runs_running enforced by SQLite).
         */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return one run + its case_results array. 404 if the id doesn't
         *     exist.
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description Scan cases/ on disk and return a summary per file.
         *
         *     Filters:
         *       * `category`: exact match (case-sensitive — categories are stable
         *         identifiers, not free text).
         *       * `q`: case-insensitive substring against id OR title.
         *
         *     Invalid YAML files are included with `status="invalid"` and `error`
         *     populated; the endpoint never 500s on a single bad file.
         */
        get: operations["list_cases_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case
         * @description Return the full YAML text + parsed fields for one case.
         *
         *     404 if the case_id is not found under any active category's
         *     dir_path. Invalid YAML still returns 200 with `status="invalid"` and
         *     the raw text + error — the UI editor needs the raw text to let a
         *     human fix it.
         */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description List active case categories ordered by `display_order ASC`.
         *
         *     `status_whitelist` is stored as a JSON text blob in SQLite (§4.5); we
         *     parse it here so the response is a clean JSON array. Malformed JSON
         *     is surfaced as an empty list rather than crashing — the row is then
         *     visibly broken in the UI and a human can fix it.
         */
        get: operations["list_categories_admin_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CaseDetail */
        CaseDetail: {
            /** Id */
            id: string;
            /** Category */
            category?: string | null;
            /** Title */
            title?: string | null;
            /** Status */
            status: string;
            /** Destructive */
            destructive?: boolean | null;
            /** Tags */
            tags?: string[] | null;
            /** Yaml Raw */
            yaml_raw: string;
            /** Parsed */
            parsed?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /** CaseResultOut */
        CaseResultOut: {
            /** Case Id */
            case_id: string;
            /** Status */
            status?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Skip Reason */
            skip_reason?: string | null;
            /** Expect Detail */
            expect_detail?: string | null;
            /** Artifacts Path */
            artifacts_path?: string | null;
        };
        /** CaseSummary */
        CaseSummary: {
            /** Id */
            id: string;
            /** Category */
            category?: string | null;
            /** Title */
            title?: string | null;
            /** Status */
            status: string;
            /** Destructive */
            destructive?: boolean | null;
            /** Tags */
            tags?: string[] | null;
            /** Error */
            error?: string | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string | null;
            /** Id Prefix */
            id_prefix: string;
            /** Dir Path */
            dir_path: string;
            /** Status Whitelist */
            status_whitelist: string[];
            /** Default Status */
            default_status: string;
            /** Display Order */
            display_order: number;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Case Ids */
            case_ids?: string[] | null;
            /** Target Version */
            target_version?: string | null;
            /** Triggered By */
            triggered_by?: string | null;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /** Run Id */
            run_id: number;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Location */
            location: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Total */
            total?: number | null;
            /** Passed */
            passed?: number | null;
            /** Failed */
            failed?: number | null;
            /** Skipped */
            skipped?: number | null;
            /** Target Version */
            target_version?: string | null;
            /** Triggered By */
            triggered_by?: string | null;
            /**
             * Case Results
             * @default []
             */
            case_results: components["schemas"]["CaseResultOut"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Total */
            total?: number | null;
            /** Passed */
            passed?: number | null;
            /** Failed */
            failed?: number | null;
            /** Skipped */
            skipped?: number | null;
            /** Target Version */
            target_version?: string | null;
            /** Triggered By */
            triggered_by?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: {
                category?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_admin_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
}
