/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Return the most recent runs (newest first), capped at `limit`.
         *
         *     Optional `case_id` query param filters to runs that touched the
         *     given case (post-M6 UX, 2026-05-25). Example:
         *     `GET /runs?case_id=bug-0009-union-all-const-distributed-row-order`
         *     returns only runs whose case_results array contains that case.
         */
        get: operations["list_runs_runs_get"];
        put?: never;
        /**
         * Create Run
         * @description Create a run row and spawn the orchestrator in the background.
         *
         *     Returns 202 with `{run_id, status, started_at, location}`. The
         *     `Location` header also points to `/runs/<id>` for the standard REST
         *     pattern.
         *
         *     Returns 409 with `{detail, active_run_id}` if another run is already
         *     in flight (uniq_runs_running enforced by SQLite).
         *
         *     v1.17+ auth: requires Bearer token. Auto-fills `triggered_by` with
         *     the authenticated user's username if the client doesn't supply one
         *     (single-user mode = always 'admin'). External curl scripts can still
         *     override by explicitly sending `triggered_by` in the body (e.g. CI
         *     bots want a distinct name).
         */
        post: operations["create_run_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description Return one run + its case_results array. 404 if the id doesn't
         *     exist.
         */
        get: operations["get_run_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run
         * @description SSE stream of run events.
         *
         *     Browser usage:
         *         const es = new EventSource(`/runs/${id}/stream`);
         *         es.onmessage = (e) => { ... JSON.parse(e.data) ... };
         *         es.onerror = () => es.close();
         *
         *     Headers `Cache-Control: no-cache` + `X-Accel-Buffering: no` ensure
         *     proxies don't buffer the stream.
         */
        get: operations["stream_run_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cases/{case_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Case Artifacts
         * @description List artifact files for one case in a run.
         *
         *     Empty list = case ran but produced no artifact files (e.g., all
         *     steps had empty stdout/stderr). 404 = run/case unknown OR artifacts
         *     dir gone.
         */
        get: operations["list_case_artifacts_runs__run_id__cases__case_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{run_id}/cases/{case_id}/artifacts/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Case Artifact
         * @description Download one artifact file as text/plain attachment.
         *
         *     Path-traversal protection: reject filenames containing path
         *     separators or `..`; further, verify the resolved path is inside
         *     the case's artifacts dir (defense-in-depth against symlinks).
         */
        get: operations["download_case_artifact_runs__run_id__cases__case_id__artifacts__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Cases
         * @description Scan cases/ on disk and return a summary per file.
         *
         *     Filters:
         *       * `category`: exact match (case-sensitive — categories are stable
         *         identifiers, not free text).
         *       * `q`: case-insensitive substring against id, title, description,
         *         or tags (joined). The skill at ``.claude/skills/add-test-case``
         *         uses this to surface near-duplicate cases when authoring a new
         *         one — searching only id+title misses dups where the author chose
         *         a different phrasing in the title but the same domain words appear
         *         in description/tags.
         *
         *     Invalid YAML files are included with `status="invalid"` and `error`
         *     populated; the endpoint never 500s on a single bad file.
         */
        get: operations["list_cases_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case
         * @description Return the full YAML text + parsed fields for one case.
         *
         *     404 if the case_id is not found under any active category's
         *     dir_path. Invalid YAML still returns 200 with `status="invalid"` and
         *     the raw text + error — the UI editor needs the raw text to let a
         *     human fix it.
         */
        get: operations["get_case_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/{case_id}/recent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Case Recent Runs
         * @description List most recent runs that touched this case (M5-3 cross-page link).
         *
         *     Returns up to `limit` (default 20) `(case_result, run)` rows joined
         *     on `case_results.run_id = runs.id`, ordered by `runs.started_at` DESC.
         *     Empty list when the case has never appeared in any run — that's not
         *     an error.
         *
         *     §14 R26: delegates to ``sqlite_store.list_recent_runs_for_case`` — no
         *     inline SQL. Storage module is the single source of truth for the
         *     `case_results` table queries.
         */
        get: operations["get_case_recent_runs_cases__case_id__recent_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Case
         * @description Validate a raw YAML case payload without persisting anything.
         *
         *     Delegates to the same modules the GET /cases path uses (§14 R26):
         *
         *     * :func:`app.storage.yaml_loader.load_case` for §4.1 schema checks
         *     * :func:`app.runner.case_normalizer.normalize_case` for step-kind /
         *       template-field checks the schema layer doesn't catch.
         *
         *     Inline copies of either module's logic would be a dual-code-path
         *     violation (§14 R26 — the bug this endpoint exists to prevent in the
         *     Web 录入 path); both modules are imported and visibly called below.
         *
         *     The validation logic lives in :func:`_validate_yaml_text` which is
         *     also reused by ``/cases/try`` — two endpoints, one validator.
         */
        post: operations["validate_case_cases_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/try": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Try Case
         * @description Trial-run a YAML case in-memory without writing to DB / cases/.
         *
         *     Pipeline (design.md §13.7 M3a-2 + §14 R26):
         *
         *     1. Hash the raw YAML (sha256) so M3a-3.5 can later cache "this
         *        payload was Try-PASSED at T" and gate ``/cases/submit`` on it.
         *     2. Validate via :func:`_validate_yaml_text` (the same helper
         *        ``/cases/validate`` uses — single validator, two callers). On
         *        failure: short-circuit, return ok=false + validation_errors,
         *        step_results=[].
         *     3. Reuse the same runner stack POST /runs uses (§14 R26):
         *        :func:`normalize_case` → :func:`dsn_map_from_env` →
         *        :class:`SqlSessionPool` → :func:`orchestrator.run_case`.
         *        Inline-recreating any of these would be a dual-code-path violation.
         *     4. Artifacts go to a tempdir that's wiped on return — Try never
         *        persists.
         *     5. Map :class:`CaseExecutionResult` → :class:`TryResponse`, truncating
         *        stderr to 500 chars per step (UI-friendly preview).
         *     6. On overall pass, write ``yaml_sha256 → now(UTC)`` into the
         *        ``app.state.try_pass_cache`` so a subsequent ``/cases/submit`` with
         *        the same exact YAML can satisfy the §6.2 three-gate without
         *        re-running. Without this write the cache is dead infrastructure
         *        and submit's gate rejects everything.
         *
         *     NOTE: This endpoint deliberately calls ``orchestrator.run_case`` (NOT
         *     ``run_suite``). ``run_suite`` persists to ``case_results`` via
         *     ``insert_case_result_fn`` — we don't want Try output polluting the
         *     production DB. ``run_case`` is the same function ``run_suite`` calls
         *     internally, so we're exercising the identical execution code path
         *     minus the DB write.
         */
        post: operations["try_case_cases_try_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Case
         * @description Submit a validated, recently-Try'd case YAML as a PR (§13.7 M3a-3).
         *
         *     Algorithm:
         *
         *     1. Hash the YAML (sha256) and check it against the Try-pass cache
         *        (§6.2 three-gate / §13.7 M3a-3.5). Missing/stale → 400.
         *     2. Re-validate via :func:`_validate_yaml_text` (defense in depth — the
         *        cache hit means *some* prior Try passed, but the YAML may have
         *        drifted since then via a different Try; re-validation closes the
         *        window where a stale hit is reused).
         *     3. Resolve `repo_root` via :func:`_resolve_repo_root` (§14 R27 — env
         *        override or `__file__`-anchored default, never cwd-implicit).
         *     4. Resolve `cases_root` via :func:`_cases_root`, look up the category's
         *        `dir_path` from the DB, and write the YAML to disk.
         *     5. DRY-RUN guard: if ``LBR_GITHUB_DRY_RUN=1``, return a fake response
         *        without touching git/gh — tests + dev env exercise the full path
         *        up to disk write without pushing to a real remote.
         *     6. Otherwise run the git+gh subprocess chain with explicit ``cwd=``
         *        (§14 R27), parse PR URL from `gh pr create` stdout, arm auto-merge.
         *
         *     Failure modes are surfaced as HTTPException — never let a
         *     ``subprocess.CalledProcessError`` bubble as a 500 without context.
         */
        post: operations["submit_case_cases_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cases/generate-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Draft
         * @description Generate a §4.1-shaped YAML case draft from a free-text description.
         *
         *     Design.md §5.4 + §13.13 v1.25 amendment. The endpoint is a thin
         *     contract layer:
         *
         *     1. Validate `len(description) <= 8 KB` (413 on overflow).
         *     2. Resolve allowed categories + status_whitelists from
         *        ``case_categories`` and build the system prompt via
         *        :mod:`app.api.llm_prompt`.
         *     3. Call ``anthropic.Anthropic().messages.create`` with
         *        ``max_tokens=2000``, ``model="claude-opus-4-7"``.
         *        a. On a 5xx / 429 / timeout / network error → no retry, raise
         *           mapped HTTPException immediately (retrying just burns more
         *           quota).
         *        b. On a successful call whose body fails ``yaml_loader.load_case``
         *           + ``case_normalizer.normalize_case`` validation → retry with
         *           the previous validation error embedded in the next prompt's
         *           user-turn (capped at 2 retries, so 3 calls total).
         *     4. After max retries, return 200 with empty ``yaml_draft`` and the
         *        accumulated validation errors — that's a business state, not a
         *        5xx.
         *
         *     §14 R26: validation goes through the same modules ``POST /cases/validate``
         *     uses (``_validate_yaml_text``). No inline schema check — if the
         *     contract drifts there, this endpoint inherits it for free.
         */
        post: operations["generate_draft_cases_generate_draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Categories
         * @description List active case categories ordered by `display_order ASC`.
         *
         *     `status_whitelist` is stored as a JSON text blob in SQLite (§4.5); we
         *     parse it here so the response is a clean JSON array. Malformed JSON
         *     is surfaced as an empty list rather than crashing — the row is then
         *     visibly broken in the UI and a human can fix it.
         */
        get: operations["list_categories_admin_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/step-kinds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Step Kinds
         * @description Return the static step-kind registry in declared order.
         *
         *     Order is preserved from `STEP_KINDS` so the skill can rely on
         *     positional references in its prompt template.
         */
        get: operations["list_step_kinds_admin_step_kinds_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/skip-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Skip List Entries
         * @description List all skip-list entries (ordered by id).
         */
        get: operations["list_skip_list_entries_admin_skip_list_get"];
        put?: never;
        /**
         * Create Skip List Entry
         * @description Add a new skip-list entry. Idempotent on duplicate (case_id, version)?
         *     No — duplicates are allowed; the orchestrator's matching rule will
         *     take any of them (first match wins per §5.3 contract).
         */
        post: operations["create_skip_list_entry_admin_skip_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/skip-list/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Skip List Entry
         * @description Remove a skip-list entry by id. 404 if missing.
         */
        delete: operations["delete_skip_list_entry_admin_skip_list__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Case
         * @description Remove a case YAML file from disk. 404 if no file matches.
         *
         *     Historical runs are preserved automatically (case_results rows hold
         *     case_id as a string, no FK). Caller is expected to `git rm + commit +
         *     push` after — the endpoint only touches the working tree.
         */
        delete: operations["delete_case_admin_cases__case_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/external-services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List External Services
         * @description List all `external/<svc>.yml` files with their raw YAML content.
         *
         *     Read-only on purpose: the file is the source of truth, edits go via
         *     `vi external/<svc>.yml` + git commit. Web UI is just a discovery /
         *     sanity-check view (e.g. "what does ES URL look like right now?").
         *
         *     Honors `EXTERNAL_DEPS_DIR` env var like the loader. Missing dir →
         *     empty list (no error; first-time setup is OK).
         */
        get: operations["list_external_services_admin_external_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/target-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Target Versions
         * @description List target versions ordered by ``display_order ASC, name ASC``.
         *
         *     Query: ``?active=true`` returns only ``is_active=1`` rows (frontend
         *     dropdown uses this). No filter / ``?active=false`` returns
         *     everything (admin CRUD page uses this).
         *
         *     GET is open (no auth) — matches ``/admin/categories``.
         */
        get: operations["list_target_versions_admin_target_versions_get"];
        put?: never;
        /**
         * Create Target Version
         * @description Add a new target_version row.
         *
         *     400 if ``name`` is empty / whitespace.
         *     409 on UNIQUE collision (duplicate ``name``).
         *     When ``is_default=true``, other rows' ``is_default`` is cleared
         *     transactionally so the at-most-one invariant holds.
         */
        post: operations["create_target_version_admin_target_versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/target-versions/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Target Version
         * @description Delete a target_version row.
         *
         *     Default behaviour: refuse with 409 if any ``runs.target_version``
         *     row references the version's ``name`` — historical runs would
         *     otherwise lose dropdown-grounding for the version they were
         *     triggered against. Pass ``?force=true`` to override.
         *
         *     404 on unknown id.
         */
        delete: operations["delete_target_version_admin_target_versions__vid__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Target Version
         * @description Partial update. Only fields present in the body are touched.
         *
         *     404 on unknown id; 400 if ``name`` is supplied but empty/whitespace;
         *     409 on UNIQUE collision with another row's name. ``is_default=true``
         *     clears other rows' is_default in the same transaction.
         */
        patch: operations["patch_target_version_admin_target_versions__vid__patch"];
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Validate credentials, mint a new token, return it.
         *
         *     No rate limiting — single-user tool, attacker would need to brute-force
         *     bcrypt remote (slow by design). If exposed publicly later, add a
         *     middleware-level rate limit.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Invalidate current token (idempotent: missing header → still 204).
         *
         *     Doesn't use get_current_user dependency — even invalid/missing tokens
         *     should not error out logout (we want clients to be able to "clear"
         *     state reliably).
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Used by frontend to bootstrap state on page load + decide whether
         *     to show the "please change password" banner.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change Password
         * @description Verify current_password → update password_hash + password_changed_at.
         *
         *     Does NOT invalidate other active tokens (simple; user can manually
         *     logout other devices if needed). Frontend banner ("please change
         *     password") disappears once password_changed_at is set.
         *
         *     Minimum new password length = 4 chars (lax; single-user tool, user
         *     knows their own strength preference).
         */
        post: operations["change_password_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArtifactInfo
         * @description One artifact file under a case's artifacts_path (M6-2).
         *
         *     `step_idx` / `step_id` populated when filename matches the runner's
         *     `step-NN-stepid.{stdout,stderr,error,log}.txt` pattern; else None
         *     (file written by something else, kept for transparency).
         *
         *     `kind` values:
         *       * `stdout`  — driver stdout buffer
         *       * `stderr`  — driver stderr buffer (NOTICE/WARNING etc.)
         *       * `error`   — driver-level exception text (e.g. psycopg.errors.*
         *                     from sql_driver._err()); only written when the
         *                     StepResult.error field is non-empty
         *       * `log`     — auxiliary log captured by the runner
         *       * `other`   — filename did not match the per-step pattern
         */
        ArtifactInfo: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /** Kind */
            kind: string;
            /** Step Idx */
            step_idx?: number | null;
            /** Step Id */
            step_id?: string | null;
        };
        /** CaseDetail */
        CaseDetail: {
            /** Id */
            id: string;
            /** Category */
            category?: string | null;
            /** Title */
            title?: string | null;
            /** Status */
            status: string;
            /** Destructive */
            destructive?: boolean | null;
            /** Tags */
            tags?: string[] | null;
            /** Yaml Raw */
            yaml_raw: string;
            /** Parsed */
            parsed?: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error?: string | null;
        };
        /**
         * CaseRecentRunOut
         * @description One row of `GET /cases/:id/recent-runs` (M5-3 cross-page link).
         */
        CaseRecentRunOut: {
            /** Run Id */
            run_id: number;
            /** Run Status */
            run_status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Case Status */
            case_status?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Target Version */
            target_version?: string | null;
        };
        /** CaseResultOut */
        CaseResultOut: {
            /** Case Id */
            case_id: string;
            /** Status */
            status?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Skip Reason */
            skip_reason?: string | null;
            /** Expect Detail */
            expect_detail?: string | null;
            /** Artifacts Path */
            artifacts_path?: string | null;
        };
        /** CaseSummary */
        CaseSummary: {
            /** Id */
            id: string;
            /** Category */
            category?: string | null;
            /** Title */
            title?: string | null;
            /** Status */
            status: string;
            /** Destructive */
            destructive?: boolean | null;
            /** Tags */
            tags?: string[] | null;
            /** Error */
            error?: string | null;
        };
        /** CategoryOut */
        CategoryOut: {
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Description */
            description: string | null;
            /** Id Prefix */
            id_prefix: string;
            /** Dir Path */
            dir_path: string;
            /** Status Whitelist */
            status_whitelist: string[];
            /** Default Status */
            default_status: string;
            /** Display Order */
            display_order: number;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** CreateRunRequest */
        CreateRunRequest: {
            /** Case Ids */
            case_ids?: string[] | null;
            /** Target Version */
            target_version?: string | null;
            /** Triggered By */
            triggered_by?: string | null;
        };
        /** CreateRunResponse */
        CreateRunResponse: {
            /** Run Id */
            run_id: number;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Location */
            location: string;
        };
        /**
         * ExternalServiceOut
         * @description One row in the /admin/external-services response.
         *
         *     `content` is the raw YAML text — not parsed — so the UI can render
         *     it verbatim (preserves comments, blank lines, etc.). Frontend does
         *     not edit; if a user wants to change a value, they edit the file
         *     directly + commit (single source of truth = `external/<svc>.yml`
         *     on disk, git-tracked).
         */
        ExternalServiceOut: {
            /** Name */
            name: string;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Modified At
             * Format: date-time
             */
            modified_at: string;
            /** Content */
            content: string;
            /** Parse Error */
            parse_error?: string | null;
        };
        /**
         * GenerateDraftRequest
         * @description Request shape for ``POST /cases/generate-draft`` (M7-1).
         */
        GenerateDraftRequest: {
            /** Description */
            description: string;
            /** Category */
            category?: string | null;
        };
        /**
         * GenerateDraftResponse
         * @description Response shape for ``POST /cases/generate-draft`` (M7-1).
         *
         *     Note ``yaml_draft`` may be the empty string when all retries failed
         *     schema validation; in that case ``attempts == 3`` and
         *     ``validation_errors_during_retry`` is non-empty. This is a business
         *     state, NOT an HTTP error — the endpoint returns 200 so the frontend
         *     can surface the errors to the user.
         */
        GenerateDraftResponse: {
            /** Yaml Draft */
            yaml_draft: string;
            /** Attempts */
            attempts: number;
            /** Validation Errors During Retry */
            validation_errors_during_retry: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Db */
            db: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Token */
            token: string;
            /** Username */
            username: string;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** MeResponse */
        MeResponse: {
            /** Username */
            username: string;
            /** Must Change Password */
            must_change_password: boolean;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Total */
            total?: number | null;
            /** Passed */
            passed?: number | null;
            /** Failed */
            failed?: number | null;
            /** Skipped */
            skipped?: number | null;
            /** Errored */
            errored?: number | null;
            /** Target Version */
            target_version?: string | null;
            /** Triggered By */
            triggered_by?: string | null;
            /**
             * Case Results
             * @default []
             */
            case_results: components["schemas"]["CaseResultOut"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: number;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Total */
            total?: number | null;
            /** Passed */
            passed?: number | null;
            /** Failed */
            failed?: number | null;
            /** Skipped */
            skipped?: number | null;
            /** Errored */
            errored?: number | null;
            /** Target Version */
            target_version?: string | null;
            /** Triggered By */
            triggered_by?: string | null;
        };
        /** SkipListCreate */
        SkipListCreate: {
            /** Case Id */
            case_id: string;
            /** Reason */
            reason: string;
            /** Applies To Version */
            applies_to_version?: string | null;
            /** Upstream Issue */
            upstream_issue?: string | null;
            /** Until Date */
            until_date?: string | null;
        };
        /** SkipListEntryOut */
        SkipListEntryOut: {
            /** Id */
            id: number;
            /** Case Id */
            case_id: string;
            /** Reason */
            reason: string;
            /** Applies To Version */
            applies_to_version?: string | null;
            /** Upstream Issue */
            upstream_issue?: string | null;
            /** Until Date */
            until_date?: string | null;
        };
        /**
         * StepKindOut
         * @description One entry in the `/admin/step-kinds` response.
         *
         *     Mirrors `app.runner.step_kinds.StepKindMeta` — the skill reads this
         *     to ground its prompt about which step kinds (and which fields per
         *     kind) are legal. No DB lookup; static registry.
         */
        StepKindOut: {
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Required Fields */
            required_fields: string[];
            /** Optional Fields */
            optional_fields: string[];
        };
        /** StepResultOut */
        StepResultOut: {
            /** Step Id */
            step_id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms?: number | null;
            /** Stderr Preview */
            stderr_preview?: string | null;
            /** Error */
            error?: string | null;
        };
        /** SubmitRequest */
        SubmitRequest: {
            /** Yaml */
            yaml: string;
            /** Case Id */
            case_id: string;
            /** Branch Name */
            branch_name: string;
        };
        /** SubmitResponse */
        SubmitResponse: {
            /** Pr Url */
            pr_url: string;
            /** Pr Number */
            pr_number: number;
            /** Branch */
            branch: string;
        };
        /** TargetVersionCreate */
        TargetVersionCreate: {
            /** Name */
            name: string;
            /**
             * Display Order
             * @default 100
             */
            display_order: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** TargetVersionOut */
        TargetVersionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Display Order */
            display_order: number;
            /** Is Active */
            is_active: boolean;
            /** Is Default */
            is_default: boolean;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TargetVersionUpdate */
        TargetVersionUpdate: {
            /** Name */
            name?: string | null;
            /** Display Order */
            display_order?: number | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Is Default */
            is_default?: boolean | null;
            /** Notes */
            notes?: string | null;
        };
        /** TryRequest */
        TryRequest: {
            /** Yaml */
            yaml: string;
        };
        /** TryResponse */
        TryResponse: {
            /** Ok */
            ok: boolean;
            /** Yaml Sha256 */
            yaml_sha256: string;
            /** Step Results */
            step_results: components["schemas"]["StepResultOut"][];
            /**
             * Validation Errors
             * @default []
             */
            validation_errors: {
                [key: string]: string;
            }[];
        };
        /** ValidateErrorItem */
        ValidateErrorItem: {
            /** Where */
            where: string;
            /** Reason */
            reason: string;
        };
        /** ValidateRequest */
        ValidateRequest: {
            /** Yaml */
            yaml: string;
        };
        /** ValidateResponse */
        ValidateResponse: {
            /** Ok */
            ok: boolean;
            /** Errors */
            errors: components["schemas"]["ValidateErrorItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_runs_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                case_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_runs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_runs__run_id__stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_case_artifacts_runs__run_id__cases__case_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_case_artifact_runs__run_id__cases__case_id__artifacts__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
                case_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_cases_get: {
        parameters: {
            query?: {
                category?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_recent_runs_cases__case_id__recent_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseRecentRunOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_case_cases_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    try_case_cases_try_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_case_cases_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_draft_cases_generate_draft_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_admin_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    list_step_kinds_admin_step_kinds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepKindOut"][];
                };
            };
        };
    };
    list_skip_list_entries_admin_skip_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkipListEntryOut"][];
                };
            };
        };
    };
    create_skip_list_entry_admin_skip_list_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipListCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkipListEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_skip_list_entry_admin_skip_list__entry_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_case_admin_cases__case_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_external_services_admin_external_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalServiceOut"][];
                };
            };
        };
    };
    list_target_versions_admin_target_versions_get: {
        parameters: {
            query?: {
                active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_target_version_admin_target_versions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_target_version_admin_target_versions__vid__delete: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_target_version_admin_target_versions__vid__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                vid: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetVersionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
